### ISSUE TITLE
Traceback error 

### ISSUE THREAD

**Issue by daniaghannam** [albinowax/ActiveScanPlusPlus#9]
Hello everyone 

please , can someone tell me how to fix this error 
I used this script 
https://github.com/MyRobotLab/inmoov/blob/develop/InMoov/testScripts/InMoov.minimalFingerStarter.py

------Traceback (most recent call last):  File string, line 50, 
in moduleAttributeError: org.myrobotlab.service.InMoovHand object has no attribute setAutoEnable
	at org.python.core.Py.AttributeError(Py.java:205)	
at org.python.core.PyObject.noAttributeError(PyObject.java:1013)	
at org.python.core.PyObject.__getattr__(PyObject.java:1008)	
at org.python.pycode._pyx5.f$0(string:84)	
at org.python.pycode._pyx5.call_function(string)	

at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.Py.runCode(Py.java:1386)	
at org.python.core.Py.exec(Py.java:1430)	
at org.python.util.PythonInterpreter.exec(PythonInterpreter.java:267)
	at org.myrobotlab.service.Python$PIThread.run(Python.java:160)------

**Comment by albinowax** [comment]
This place is for reporting bugs in activeScan++ only. Try https://github.com/MyRobotLab/inmoov/issues
